/** Context only. These retained wiki rows do not define Engine capabilities or balance. */
export const retainedProgressionReference = [
  'Retained BTD6 progression examples: community wiki upgrade rows accessed 2026-09-20, not a pinned game-build audit or current balance certification. Prices below are incremental Medium purchases. Retained overview, total-cost, crosspath and version-history sections sometimes disagree; use the identified upgrade rows as historical examples, not universal multipliers or a required price curve.',
  'Dart bottom path: T3 Crossbow costs 575, deals 3 damage and reaches 60 range. T4 Sharp Shooter costs 2050, deals 6 ordinary damage, changes the interval from 0.95s to 0.475s, and adds a 50-damage critical every 10 shots. T5 Crossbow Master costs 21500, deals 8 ordinary damage, attacks every 0.2375s, raises pierce from 4 to 8 and range from 60 to 80, and delivers an 80-damage critical every 5 shots. The retained row also grants all-type damage access. T4 buys a stronger precision weapon and recurring spikes; T5 buys much faster sustained fire, more frequent spikes, reach and group capacity together. Its high incremental price does not imply that it always beats several cheaper towers.',
  'Dart tradeoff: 2-0-5 benefits from extra pierce when a straight lane supplies enough targets; 0-2-5 fires faster and reaches its shot-count critical sooner in elapsed time. Extra pierce is unused against one isolated target, while multiple cheap placements need space and useful firing coverage. Critical counters, projectile travel and per-type damage permissions are unsupported analogies here unless the supplied Definition explicitly implements them; ordinary damage is not a critical-hit system.',
  'Boomerang middle path: T3 Bionic Boomerang costs 1250, fires 8x faster than the ordinary base tower and adds 1 damage to MOAB-class targets. T4 Turbo Charge costs 4200 and temporarily fires 5x faster with 1 extra damage for 10s on a 45s cooldown. T5 Perma Charge costs 35000, makes the former Turbo speed permanent, deals 4 ordinary damage, and retains an active adding 8 damage for 15s. This retained effect row does not specify the T5 cooldown; do not invent it. T4 buys a timed answer to a dangerous push; T5 buys a much stronger permanent firing state plus a further burst, rather than merely extending one stat by a universal ratio.',
  'Boomerang tradeoff: 2-4-0 adds pierce for dense groups; 0-4-2 adds damage and Lead access for tougher targets but can leave weaker cleanup after blimps break apart. A timed burst needs threats inside range during activation, and most builds still need Camo support. Enemy-class damage bonuses, Lead exceptions and curved or returning trajectories remain unsupported analogies; the Definition may support an ordinary attack boost without reproducing these other effects.',
  'Sources: research/btd6/source-snapshots/btd6-dart-2026-09-20.txt, upgrade rows at lines 79, 85 and 91, https://bloons.fandom.com/wiki/Dart_Monkey_(BTD6); research/btd6/source-snapshots/btd6-dart-crosspaths-2026-09-20.txt, Crossbow Master discussion at lines 115-124, https://bloons.fandom.com/wiki/Crosspathing/Dart_Monkey. Boomerang: research/btd6/source-snapshots/btd6-boomerang-2026-09-20.txt, upgrade rows at lines 48, 54 and 60, https://bloons.fandom.com/wiki/Boomerang_Monkey_(BTD6); research/btd6/source-snapshots/btd6-boomerang-crosspaths-2026-09-20.txt, Turbo Charge discussion at lines 90-93, https://bloons.fandom.com/wiki/Crosspathing/Boomerang_Monkey.',
].join('\n');
