package unit

import "strings"

// Model-facing default text. Change it deliberately and raise the version.

// StarterTask is the bundled Profile task.
const StarterTask = "Adapt the character into one Tower Defense Unit from a faithful subset of the supplied source evidence. Plan the character's repertoire and three behaviorally distinct paths before choosing numbers, then implement one automatic base attack and all fifteen purchases with the supported mechanics. Use build codes such as 0-0-0, 3-x-x and 1-2-0. Preserve source ownership and story period, list behavior the Definition cannot express as unsupported mechanics, and label all numbers and prices as proposals. Do not claim canon verification or balance."

// atlasCapture pins the BTD6 reference values of the default Profile.
const atlasCapture = "btd6-atlas capture 56.3, Steam build 24829026, repository revision a380413 (https://github.com/KyleDerZweite/btd6-atlas/tree/a380413ed809c98654acec7aa37cba40f80bf5c5/data/56.3-build-24829026)"

// defaultRulesSections are the paragraphs of the bundled rules document.
var defaultRulesSections = []string{
	"Character Tower Defense rules, version 13, for the BTD6-inspired default Profile. Editable starter rules, not Manga Mayhem rules, BTD6 canon or balance certification. The structured mechanicsDefinition owns executable operators, numerical limits and the starter scale. The atlas references below show scale and progression shape; they are not kits to copy.",

	"Source fidelity. Adapt the character's sourced attacks, weapons, forms, sensory powers and interactions. Respect ownership, prerequisites and story period: another actor using a power does not establish that this character owns it, and former or conditional powers keep their limits. Keep invented Tower Defense interactions separate from canon claims. A revision that only edits wording keeps every supplied mechanic; a redesign names each deliberate change and never resolves a contradiction silently.",

	"Build codes. Paths are top, middle and bottom, with five sequential purchases each. Write builds top-middle-bottom: 0-0-0 is the base Unit; 1-x-x to 5-x-x are top purchases, x-1-x to x-5-x middle and x-x-1 to x-x-5 bottom; x means unspecified, not a free purchase; 1-2-0 is a concrete build. A Unit buys at most two paths and only one beyond its second purchase: 3-2-0 is legal, 3-3-0 and 1-1-1 are not. Purchased effects persist unless a later purchase explicitly replaces them.",

	"Activation. Only the middle path may have a player-activated ability, first at x-4-x; top and bottom stay automatic, and choosing a targeting priority is not an activation. In this Definition the ability is one manual boost of the Unit's purchased attack: x-4-x unlocks it and x-5-x may modify that same boost. A second x-5-x Active, a ground-targeted strike, a separate Active attack, allied restoration and dispels cannot be expressed. Record them as unsupported mechanics and keep them out of names and wording.",

	"Purchase roles. The first and second purchase of each path are small readable foundations that stay useful as crosspaths: they improve the existing attack and may add personal detection, never a broad all-source damage buff. The third purchase creates a reason to commit by adding a supported behavior or access: a new delivery, a distinct-target volley, more projectiles, splash, a status effect, a bounded follow-up, a new damage type or a new detection trait, chosen from the character; larger numbers or a targeting change alone are not enough. The fourth and fifth develop, add or replace behavior, access, capacity or uptime as the path's role requires; they need not add a subsystem each time, but a fifth purchase that only raises ordinary damage is a token step, not a capstone. Keep the three paths behaviorally distinct and use no universal capstone multiplier.",

	"Actions. For every changed action state its trigger, target, delivery, timing, effect, inheritance and limit. Say adds when behavior coexists and replaces only when the earlier behavior stops. Do not invent shared cooldowns or suppress independent behavior. A transformation says what changes and what happens when it ends. Preserve the selected targeting and normal movement prediction of enemy-targeted attacks; ground-targeted effects are distinct. Damage, width, projectile count, area and pierce are separate properties. Chains, explosions, fragments, return passes and control need bounded hit capacity and a stated repeat-hit or pierce-refresh rule. Bound support and control by eligibility, capacity, locality or downtime; no unbounded multi-copy support or control loops.",

	"Crosspaths. Code resolves every partial and full crosspath: the 12 early builds 1-1-0, 1-2-0, 1-0-1, 1-0-2, 2-1-0, 2-2-0, 2-0-1, 2-0-2, 0-1-1, 0-1-2, 0-2-1 and 0-2-2, and the 36 advanced builds where one path is at 3 or more and another at 1 or 2. A side purchase changes the one attack and, when owned, the middle boost of that attack. Know which of them receives each change of damage, speed, range, detection, pierce and statuses; do not invent a special synergy for every combination.",

	"Match rules. A stationary Unit attacks detected enemies in range along a clear delivery path; detection grants neither delivery nor damage access. Gold is match currency and Health the shared life pool, 150 at the start; Units have no Health. The basic enemy has one layer removed by 1 damage; tougher enemies need explicit rules, and no layer tree or leak simulation exists. A player may own one placed 5-x-x, x-5-x or x-x-5 per Unit type and path at a time; the caller enforces this from match state.",

	"Engine boundary. The Definition supports one automatic base attack with its delivery, damage type, targeting, detection and status effects, one manual boost of that attack on the middle path, distinct-target volleys and bounded follow-ups. Summons, independent or ground-targeted attacks, separate Actives, allied buffs, restoration, shields, armor-only damage, magazines, reloads, critical counters, rebounds, knockback, economy and movement are unsupported: list them as unsupported mechanics. An ordinary damage stat never implements shield bypass, armor-only damage or restoration, and a name or sentence never grants missing behavior. The vocabulary names every status effect, damage type, targeting mode and detection trait; no other exists.",

	"Private design checks, never printed in the unit: why a player buys each path, which weakness remains, why a capstone beats more fourth-purchase copies, whether cheap copies stack into loops, and a review for missing effects, illegal builds, unsupported character claims, lost purchased benefits, reductions presented as upgrades, extra activation buttons, control loops and crosspaths that fail after a transformation. Code measures ordinary-target throughput, group capacity, control, reach and active windows analytically; that is evidence for review, not balance.",

	"Unit output. The rendered unit starts with the character name and 0-0-0, then each purchase by build code with its exact numbers in ordinary sentences, then the crosspath builds. Unsupported mechanics, reserved techniques and review findings are diagnostics outside the unit. It carries no strategy, balance verdicts, capability reports, rules recaps or review certificates. Names and wording use direct sentences and consistent terms; no filler, promotional wording, usage advice, em dashes or en dashes. Patch notes, when requested, separate changed mechanics from wording fixes.",

	"Scale references from " + atlasCapture + ". Prices are Medium incremental purchases; files are under game-data/Towers and game-data/Upgrades. Damage per second assumes a target always in range and ignores enemy-class bonuses unless stated.",

	"Dart Monkey 0-0-0 (DartMonkey.json): 200 Gold; one dart every 0.95 s at range 32, 1 sharp damage, pierce 2; no Camo detection; sharp damage cannot hurt Lead or Frozen. 1.05 damage per second on one target; one throw deals at most 2 damage in total.",

	"Group capacity, Dart Monkey top (DartMonkey-100 to -500): 1-0-0 Sharp Shots 140, pierce 3. 2-0-0 Razor Sharp Shots 200, pierce 5. 3-0-0 Spike-o-pult 320 replaces the dart with a rebounding spiked ball: 2 damage, pierce 18, every 1.15 s, range 36.8, can hurt Frozen. 4-0-0 Juggernaut 1800: every 1.0 s, pierce 60, can hurt Lead, +3 damage to Ceramic and +2 to Fortified, knockback. 5-0-0 Ultra-Juggernaut 15000: 5 damage, pierce 210, larger Ceramic, Fortified and Lead bonuses; when its pierce runs out the ball splits into two rings of six balls with 2 damage and pierce 50 each. Damage capacity per throw grows 2, 5, 36, 120 and 2250 while single-target damage per second grows only from 1.05 to 5: the branch buys group capacity and access, not ordinary damage.",

	"Precision, Dart Monkey bottom (DartMonkey-001 to -005): 0-0-1 Long Range Darts 90, range 40. 0-0-2 Enhanced Eyesight 200, range 48 and personal Camo detection. 0-0-3 Crossbow 575: 3 damage, pierce 4, range 60. 0-0-4 Sharp Shooter 2050: 6 damage every 0.475 s; every tenth shot is a 50-damage critical. 0-0-5 Crossbow Master 21500: 8 damage every 0.2375 s, pierce 8, range 80, hurts every type; every fifth shot is an 80-damage critical. Counting a critical shot as its critical damage, single-target damage per second is 3.2, about 22 and about 94: each advanced purchase multiplies precise damage and the capstone also adds reach, pierce and access.",

	"Attack speed with an allied active, Dart Monkey middle (DartMonkey-010 to -050): 0-1-0 Quick Shots 100, every 0.8075 s. 0-2-0 Very Quick Shots 190, every 0.6365 s. 0-3-0 Triple Shot 450: three darts in a 30 degree arc every 0.477 s. 0-4-0 Super Monkey Fan Club 7200: every 0.239 s; an activated ability for 15 s, recharging in 50 s, turns up to 10 nearby Dart Monkeys with no path above 2 into super monkeys that attack at about 0.063 times their interval. 0-5-0 Plasma Monkey Fan Club 45000: same timing, up to 20 monkeys, +1 damage and +3 pierce on their darts. Darts per second grow 1.05, 1.24, 1.57, 6.3 and 12.6; most value of x-4-x and x-5-x lies in allies, which this Definition cannot express.",

	"Attack speed with a self active, Boomerang Monkey middle (BoomerangMonkey.json and -010 to -050): base 315 Gold, 1 damage every 1.2 s, pierce 4, range 43, returning flight. 0-1-0 Faster Throwing 175, every 0.9 s. 0-2-0 Faster Rangs 250, every 0.6 s. 0-3-0 Bionic Boomerang 1250: every 0.15 s, 8 times the base frequency, and +1 damage to MOAB-class enemies. 0-4-0 Turbo Charge 4200: activated for 10 s, recharging in 45 s: interval times 0.2 and +1 damage. 0-5-0 Perma Charge 35000: permanently every 0.03 s with 4 damage; its active adds 10 damage for 15 s, recharging in 45 s. Single-target damage per second is 0.83, 6.7 at 0-3-0, 67 during the 0-4-0 active (22 percent uptime), 133 permanently at 0-5-0 and 467 during its active. Pierce stays 4, so group capacity grows only through frequency.",

	"Single target with blimp control, Sniper Monkey top (SniperMonkey.json and -100 to -500): base 350 Gold, instant 2 damage every 1.59 s on one target anywhere on the map; no Camo detection; cannot hurt Lead or Frozen. 1-0-0 Full Metal Jacket 350: 4 damage and Lead and Frozen access. 2-0-0 Large Calibre 1300: 7 damage. 3-0-0 Deadly Precision 2200: 20 damage and +50 to Ceramic. 4-0-0 Maim MOAB 6300: 30 damage; each hit immobilizes MOAB-class enemies for 3 s on a MOAB down to 0.75 s on a ZOMG or DDT. 5-0-0 Cripple MOAB 32000: 140 damage, immobilizes for up to 7 s, hit MOAB-class enemies take 5 extra damage per hit, and each hit bursts for 28 damage on up to 10 enemies within 8. Damage per second is 1.3, 2.5, 4.4, 12.6, 18.9 and 88: the fourth purchase adds control access more than damage; the capstone multiplies damage and adds control uptime, vulnerability and a bounded burst.",

	"Control, Ice Monkey top (IceMonkey.json and -100 to -500): base 400 Gold; every 2.4 s it freezes up to 40 non-MOAB enemies within 20 for 1.5 s and deals 1 damage; no Camo detection; cannot hurt Lead or White. 1-0-0 Permafrost 150: frozen enemies keep a 50 percent slow. 2-0-0 Cold Snap 350: can freeze Lead. 3-0-0 Ice Shards 1500: range 25 and a shard effect on frozen enemies. 4-0-0 Embrittlement 2300: also slows MOAB-class enemies and freezes 3 layers instead of 2. 5-0-0 Super Brittle 28000: every 1.56 s, 5 damage, every type, 6 layers. Control exists at the base; purchases add persistence, access and uptime (freeze covers 1.5 s of every 2.4 s, then of every 1.56 s), not ordinary damage.",

	"Burst active, Tack Shooter middle (TackShooter.json and -010 to -050): base 260 Gold, a ring of 8 tacks every 1.12 s, 1 damage and pierce 1 each, range 23. 0-1-0 Long Range Tacks 100, range 26.9. 0-2-0 Super Range Tacks 225, range 30.8 and pierce 4. 0-3-0 Blade Shooter 550: blades with pierce 8, range 46, can hurt Frozen. 0-4-0 Blade Maelstrom 2700: 2 damage; an activated spin for 3 s, recharging in 20 s, fires 2 blades every 0.045 s with pierce 100 and 2 damage. 0-5-0 Super Maelstrom 15000: 5 damage, +5 to Ceramic, every type; the spin lasts 9 s on the same 20 s recharge. Ring damage capacity per second is 7, 29, 57, 114 and 286; the spin far exceeds it while it lasts, and its uptime rises from 15 to 45 percent.",

	"Support, Monkey Village (MonkeyVillage.json, -100, -200 and -020): base 1200 Gold and no attack; allied towers within 40 gain 10 percent range. 1-0-0 Bigger Radius 400, radius 48. 2-0-0 Jungle Drums 1500, allies attack 15 percent faster. 0-2-0 Radar Scanner 2000, allies in the radius can target Camo. Allied buffs and shared detection have no operator here; list them as unsupported mechanics.",

	"Roster shape from the atlas patterns (patterns/towers.md and progression.md): 26 standard towers; primary base prices 200 to 400; tier medians about 200 to 275 for a first purchase, 1500 to 2000 for a third, 4000 to 6500 for a fourth and 30000 to 38000 for a fifth. Final-to-previous purchase price ratios range from 1.58 to 19.64 with median 6.15; they describe prices, not output, and are not a capstone multiplier. The middle fourth purchase carries an ability in 25 of 26 towers and the fifth keeps it; top and bottom fourth purchases show one each. No fifth purchase above changes only ordinary damage.",

	"Health and layer values are starter assumptions. All generated values and prices are proposals that need playtesting.",
}

// defaultRulesText is the bundled rules document text.
var defaultRulesText = strings.Join(defaultRulesSections, "\n\n")

const defaultRulesID = "default-td-profile-v13"
const defaultRulesLocation = "mardwerk-unit:default-td-profile:v13"
const defaultRulesNote = "Bundled starter preset. Edit or replace it in Inputs and rules before preparing a custom Request."
const defaultProfileName = "BTD6-inspired (default)"
const defaultAuthoringRevision = "2026-09-26-atlas-56.3-v13"
